name: Publish new release
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  publish:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'pull_request' &&
        github.event.pull_request.merged == true &&
        contains( github.event.pull_request.labels.*.name, 'new-release')
      )
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Prepare package
        run: |
           chmod +x ./prepare-build.sh
           ./prepare-build.sh
        shell: bash

      - name: Build and publish
        run: |
           chmod +x ./build.sh
           ./build.sh
        shell: bash
        env:
          GPG_PRIVATE_KEY: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.PPA_GPG_PASSPHRASE }}
          PKGDIR: ${{ github.workspace }}/build/task-maker-rust
          REPOSITORY: ppa:dariop1/task-maker-rust
